[package]
name = "mvdis-license-plate-query"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43", features = ["full"] }
reqwest = { version = "0.13", features = ["rustls", "form"] }
scraper = { version = "0.22", features = ["atomic"] }
strum = { version = "0.26", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
reqwest_cookie_store = "0.10"
ddddocr = { git = "https://github.com/86maid/ddddocr.git", tag = "v6.0.6" }
anyhow = "1"

[dev-dependencies]
anyhow = { version = "1", features = ["backtrace"] }
futures = "0.3"
num_cpus = "1.16"
tokio = { version = "1.43", features = ["full"] }
tokio-task-pool = "0.1"
